### ISSUE TITLE
Problema con cambiar fecha en secretaria

### ISSUE THREAD

**Issue by tranfuga25s** [tranfuga25s/turneraonline#107]
Al cambiar de fecha desde la vista de turnos desde la vista de secretaria, al utilizar el botón día, se cambia a la fecha: 1/12/-0001

**Comment by daniels591** [comment]
Cambiar dia
pones alguna fecha te la da
cuando volves
para avanzar o cambiar de dia
se va al 30 / 11 / 2013
despues en la descripcion
Turnos para el día 30/11/-0001
aparece eso
no dice el año

**Comment by tranfuga25s** [comment]
Arreglado el problema con el parametro en la vista de secretarias.

**Comment by tranfuga25s** [comment]
Arreglado el problema con el parametro en la vista de médicos.
