### ISSUE TITLE
Reserva de turnos Secretaria

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/turneraonline#111]
Al reservar un turno no retorna a la lista de turnos 

Muestra lo siguiente:

/app/Controller/TurnosController.php (line 312)

array(
    'Turno' => array(
        'id_medico' => '1',
        'id_turno' => '1518',
        'controlador' => 'Secretarias',
        'rpaciente' => '8 - Sequeira, Daniel'

**Comment by tranfuga25s** [comment]
Eliminado problema.
