### ISSUE TITLE
Sobre turnos Secretaria

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/turneraonline#112]
http://www.turnossantafe.com.ar/turneraonline/turnos/sobreturno

Al realizar un sobreturno sale el siguiente error 

Fatal Error

Error: Class 'MissingParameterException' not found
File: /home/gestotux/public_html/turneraonline/app/Controller/TurnosController.php
Line: 414

Notice: If you want to customize this error message, create app/View/Errors/fatal_error.ctp

**Comment by tranfuga25s** [comment]
Se arregló el problema de la vista que muestra que falta un parámetro.

**Comment by tranfuga25s** [comment]
Se agregó el problema del sobreturno y el problema de la reserva de turnos al crear un paciente.
