### ISSUE TITLE
Turnos del dia Medico

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/turneraonline#114]
El usuario Medico, Medico no respeta la disponibilidad tampoco muestra turnos del día

**Comment by tranfuga25s** [comment]
Comprobado que los turnos se generan correctamente, verificar que el filtro de días esté funcionando correctamente.

**Comment by tranfuga25s** [comment]
Agregado listado de turnos faltantes en la vista de medicos que no estába colocado en el template nuevo.
